#! /usr/bin/perl

use lib "lib";
use Template;

chdir("page-sources");
@pages = (<*.html>);
chdir("..");

my $site_master_template           = new Template("templates/site-master.html");
my $site_menu_template             = new Template("templates/site-menu.html");

write_page("index.html",         "home");
write_page("documentation.html", "documentation");
write_page("download.html",      "download");

system("./build-examples");

sub write_page {
    my $page = shift;
    my $selected_tab = shift;

    open(OUT, ">$page");
    print OUT $site_master_template->render({
        'siteroot' => ".",
        'title'    => "Multigraph",
        'sitemenu' => $site_menu_template->render({
            $selected_tab => 'selected',
            'siteroot' => "."
         }),
        'content'  => Template::file_contents("page-sources/$page")
    });
    close(OUT);
}
